services:
  hktvmall-api:
      build: .
      image: "hktvmall-exchange-api"
      container_name: "hktmall-api"
      restart: "always"
      networks: 
          - "net"
      environment:
            HKTV_USERNAME: "YOUR-INPUT"
            HKTV_PWD: "YOUR-INPUT"
            HKTV_MERCHANT_CODE: "YOUR-INPUT"
            VIRTUAL_HOST: "YOUR-DOMAIN"
            LETSENCRYPT_HOST: "YOUR-DOMAIN"
            VIRTUAL_PORT: "80"
          
networks:
    net:
        external: true

