services:
  hktvmall-api:
      build: .
      image: "hktvmall-exchange-api"
      container_name: "hktmall-api"
      restart: "always"
      networks: 
          - "net"
      environment:
          VIRTUAL_HOST: "YOUR-VIRTUAL-HOST-DOMAIN"
          LETSENCRYPT_HOST: "YOUR-VIRTUAL-HOST-DOMAIN"
          VIRTUAL_PORT: "80"
          
networks:
    net:
        external: true

